name: buildx

on: [push, pull_request]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://repo1.maven.org/maven2/org/apache/sling/org.apache.sling.feature.launcher/1.1.20/org.apache.sling.feature.launcher-1.1.20.jar -o launcher.jar
  buildx:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmd:
          - baseimage: adoptopenjdk/openjdk8:ubuntu
            tagcmd: -t apache/sling-feature-launcher:8-jdk-ubuntu
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk8:ubuntu-jre
            tagcmd: -t apache/sling-feature-launcher:8-jre-ubuntu
            platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
            
          - baseimage: adoptopenjdk/openjdk8:ubuntu-slim
            tagcmd: -t apache/sling-feature-launcher:8-slim-ubuntu
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk11:ubuntu
            tagcmd: -t apache/sling-feature-launcher:11-jdk-ubuntu
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk11:ubuntu-jre
            tagcmd: -t apache/sling-feature-launcher:11-jre-ubuntu
            platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
            
          - baseimage: adoptopenjdk/openjdk11:ubuntu-slim
            tagcmd: -t apache/sling-feature-launcher:11-slim-ubuntu
            platforms: linux/amd64            
            
          - baseimage: adoptopenjdk/openjdk16:ubuntu
            tagcmd: -t apache/sling-feature-launcher:16-jdk-ubuntu
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk16:ubuntu-jre
            tagcmd: -t apache/sling-feature-launcher:16-jre-ubuntu
            platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
            
          - baseimage: adoptopenjdk/openjdk16:ubuntu-slim
            tagcmd: -t apache/sling-feature-launcher:16-slim-ubuntu
            platforms: linux/amd64               
            
          - baseimage: adoptopenjdk/openjdk8:alpine
            tagcmd: -t apache/sling-feature-launcher:8-jdk-apline
            platforms: linux/amd64

          - baseimage: adoptopenjdk/openjdk8:alpine-jre
            tagcmd: -t apache/sling-feature-launcher:8-jre-apline
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk8:alpine-slim
            tagcmd: -t apache/sling-feature-launcher:8-slim-apline
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk11:alpine
            tagcmd: -t apache/sling-feature-launcher:11-jdk-apline
            platforms: linux/amd64

          - baseimage: adoptopenjdk/openjdk11:alpine-jre
            tagcmd: -t apache/sling-feature-launcher:11-jre-apline
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk11:alpine-slim
            tagcmd: -t apache/sling-feature-launcher:11-slim-apline
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk16:alpine
            tagcmd: -t apache/sling-feature-launcher:16-jdk-apline
            platforms: linux/amd64

          - baseimage: adoptopenjdk/openjdk16:alpine-jre
            tagcmd: -t apache/sling-feature-launcher:16-jre-apline
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk16:alpine-slim
            tagcmd: -t apache/sling-feature-launcher:16-slim-apline
            platforms: linux/amd64

          - baseimage: adoptopenjdk/openjdk8:centos
            tagcmd: -t apache/sling-feature-launcher:8-jdk-centos
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk8:centos-jre
            tagcmd: -t apache/sling-feature-launcher:8-jre-centos
            platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
            
          - baseimage: adoptopenjdk/openjdk8:centos-slim
            tagcmd: -t apache/sling-feature-launcher:8-slim-centos
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk11:centos
            tagcmd: -t apache/sling-feature-launcher:11-jdk-centos
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk11:centos-jre
            tagcmd: -t apache/sling-feature-launcher:11-jre-centos
            platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
            
          - baseimage: adoptopenjdk/openjdk11:centos-slim
            tagcmd: -t apache/sling-feature-launcher:11-slim-centos
            platforms: linux/amd64            
            
          - baseimage: adoptopenjdk/openjdk16:centos
            tagcmd: -t apache/sling-feature-launcher:16-jdk-centos
            platforms: linux/amd64
            
          - baseimage: adoptopenjdk/openjdk16:centos-jre
            tagcmd: -t apache/sling-feature-launcher:16-jre-centos
            platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
            
          - baseimage: adoptopenjdk/openjdk16:centos-slim
            tagcmd: -t apache/sling-feature-launcher:16-slim-centos
            platforms: linux/amd64            
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          install: true

      - name: Docker Buildx (build) linux/amd64
        run: docker buildx build . -f Dockerfile --platform ${{ matrix.cmd.platforms }}  ${{ matrix.cmd.tagcmd }} --build-arg FROM_IMAGE=${{ matrix.cmd.baseimage }} 

      - name: Docker Login
        if: success() && contains(github.ref, 'master')
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Clear
        run: |
          rm -f ${HOME}/.docker/config.json 
